pipeline {
    agent any
    stages {
            stage("Build")
            {
                steps {
                        echo "Compiling the application."
                        sh "chmod 755 demo/"
                        sh "./demo/mvnw install"
                }
            }
            stage("Test") {
            steps {
                        echo "testing the application."
                        sh "chmod 755 demo/"
                        sh "./demo/mvnw test"
            }
        }
        stage("Deploy")
        {
            steps {
                //run docker
                        echo "Deploying the application"
                        sh "docker stop myApp"
                        sh "docker rm myApp"
                        sh "docker build -t my-java-app ."
                        sh "docker run -it --name myApp -p 8000:8080 my-java-app"
            }
        }
    }
    post {
        success {
                echo "Pipeline successful."
        }
        failure {
                echo "The Pipeline failed."
        }
        always {
            cleanWs()
        }
    }
}
