pipeline {
    agent any
    stages {
            stage("Build")
            {
                steps {
                        echo "Compiling the application."
                        sh "cd demo"
                        sh "pwd"
                        sh "ls -l"
                        sh './mvnw install'
                }
            }
            stage("Test") {
            steps {
                        echo "testing the application."
                        sh "cd demo"
                        sh "pwd"
                        sh "ls -l"
                        sh './mvnw test'
            }
        }
        stage("Deploy")
        {
            steps {
                //run docker
                        echo "Deploying"
                       // sh ''
            }
        }
    }
    post {
        success {
                echo "Pipeline successful."
        }
        failure {
                echo "The Pipeline failed."
        }
        always {
            cleanWs()
        }
    }
}
