pipeline {
    agent any
    stages {
            stage("Build")
            {
                steps {
                        echo "Compiling the application."
                        sh "chmod 755 demo/"
                        sh "./demo/mvnw install"
                }
            }
            stage("Test") {
            steps {
                        echo "testing the application."
                        sh "chmod 755 demo/"
                        sh "./demo/mvnw test"
            }
        }
        stage("Deploy")
        {
            steps {
                //run docker
                        echo "Deploying"
                       // sh ''
            }
        }
    }
    post {
        success {
                echo "Pipeline successful."
        }
        failure {
                echo "The Pipeline failed."
        }
        always {
            cleanWs()
        }
    }
}
